sudo: required
dist: wily

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-7-jdk gradle

before_script: 
  - gradle --version

script:
  - jdk_switcher use openjdk7
  - gradle build
