sudo: required
dist: trusty

before_install:
  - sudo apt-get install -y openjdk-8-jdk gradle haveged

before_script: 
  - jdk_switcher use openjdk8
  - gradle --version

script:
  - gradle build --stacktrace --info
